import type { CmsEntry } from "@/lib/cms/content";
import { normalizeCmsEntryAssetUrls } from "@/lib/cms/assets";

const sampleForumEntryItems: CmsEntry[] = [
  {
    authorName: "yangxi",
    body: "<p>This guide explains how to enable multilingual product detail content with <strong>Zider Product Detail Enhancer</strong>.</p>\n<p>After setup, you can create separate product detail content for each supported site language and display the correct content on your product detail page.</p>\n<h2>1. Open the Dashboard</h2>\n<p>Go to your Wix Dashboard and open <strong>Zider Product Detail Enhancer</strong> from the Apps menu.</p>\n<p>On the main dashboard, find the <strong>Zider Product Multilingual</strong> section and click <strong>Manage Languages</strong>.</p>\n<img src=\"https://assets.lopuo.com/app/zider/uploads/2026/05/01-dashboard-manage-languages.png\" alt=\"\" />\n<h2>2. Add a Language</h2>\n<p>On the <strong>Zider Product Multilingual</strong> page, click <strong>Add Language</strong>.</p>\n<p>In the dialog, search for the language you want to support, such as <strong>Traditional Chinese</strong>, <strong>Chinese</strong>, or <strong>Japanese</strong>. Select the language, then click <strong>Add Language</strong>.</p>\n<p>The main language does not need to be added. Only add non-primary languages that you want to translate.</p>\n<img src=\"https://assets.lopuo.com/app/zider/uploads/2026/05/02-add-language-modal.png\" alt=\"\" />\n<h2>3. Sync Products</h2>\n<p>After adding a language, find it in the language list and click <strong>Sync Products</strong>.</p>\n<p>The app will create product detail content records for that language. When the sync is complete, you will see a success message with the number of inserted and updated records.</p>\n<p>Example:</p>\n<pre><code>Traditional Chinese product sync complete. Inserted: 11, Updated: 0.</code></pre>\n<img src=\"https://assets.lopuo.com/app/zider/uploads/2026/05/03-sync-products-complete.png\" alt=\"\" />\n<h2>4. Edit Product Content</h2>\n<p>Click <strong>Product List</strong> at the top of the page.</p>\n<p>Use the language dropdown to select the target language, such as <strong>Traditional Chinese (zh)</strong>. The list will show the product detail records for that language.</p>\n<p>Click <strong>Edit</strong> next to a product to open its CMS item and edit the translated product detail content.</p>\n<img src=\"https://assets.lopuo.com/app/zider/uploads/2026/05/04-product-list-edit-language.png\" alt=\"\" />\n<h2>5. Enable Multilingual in the Component Settings</h2>\n<p>Open your product detail page in the Wix Editor.</p>\n<p>Select the <strong>Zider Product Detail Enhancer</strong> component and open the <strong>Zider Setting</strong> panel.</p>\n<p>Find the <strong>Multilingual</strong> switch and turn it on. Once enabled, the component will load the product detail content that matches the current site language.</p>\n<p>Click <strong>Save</strong>, then <strong>Publish</strong> your site.</p>\n<img src=\"https://assets.lopuo.com/app/zider/uploads/2026/05/05-editor-enable-multilingual.png\" alt=\"\" />\n<h2>Notes</h2>\n<ul>\n<li>Main language content is stored in the default product detail content records.</li>\n<li>For each new language, add the language first, then sync products.</li>\n<li>After syncing, edit the translated product detail content from <strong>Product List</strong>.</li>\n<li>The <strong>Multilingual</strong> switch must be enabled in the component settings for the storefront to display language-specific content.</li>\n</ul>",
    contentType: "forum",
    coverImageUrl: "https://assets.lopuo.com/app/zider/uploads/2026/05/01-dashboard-manage-languages.png",
    createdAt: "2026-05-21T06:22:25.000Z",
    excerpt: "This guide explains how to enable multilingual product detail content with Zider Product Detail Enhancer. After setup, you can create separate product detail content for each supported site language and display the corre",
    id: "community-question-zider-product-detail-enhancer-multilingual-usage-guide",
    locale: "en",
    publishedAt: "2026-05-21T06:22:25.000Z",
    slug: "zider-product-detail-enhancer-multilingual-usage-guide",
    sourceUrl: "https://zider.ink/question/zider-product-detail-enhancer-multilingual-usage-guide/",
    status: "published",
    tags: ["product detail","multilingual","wix"],
    title: "Zider Product Detail Enhancer: Multilingual Usage Guide",
    updatedAt: "2026-05-21T06:22:25.000Z",
  },
  {
    authorName: "yangxi",
    body: "<p>The simplest way to create a Before and After slider in Wix is by using an app from the Wix App Market.</p>\n<p>In most cases, the process looks like this:</p>\n<ol start=\"1\">\n<li>\n<p>Install a Before and After slider app in Wix</p>\n</li>\n<li>\n<p>Add the slider to your page</p>\n</li>\n<li>\n<p>Upload your “before” image and your “after” image</p>\n</li>\n<li>\n<p>Adjust the layout if needed</p>\n</li>\n<li>\n<p>Publish the page and test the interaction</p>\n</li>\n</ol>\n<p>Using an app is usually faster than building a custom comparison section manually.</p>\n<p>If you want a ready-to-use option, you can try <span><b>Before And After</b></span> here:</p>\n<p><a href=\"https://www.wix.com/app-market/before-and-after\">https://www.wix.com/app-market/before-and-after</a></p>",
    contentType: "forum",
    coverImageUrl: null,
    createdAt: "2026-04-18T04:19:15.000Z",
    excerpt: "The simplest way to create a Before and After slider in Wix is by using an app from the Wix App Market.In most cases, the process looks like this:Install a Before and After slider app in WixAdd the slider to your pageUpl",
    id: "community-question-how-do-you-create-a-before-and-after-slider-in-wix",
    locale: "en",
    publishedAt: "2026-04-18T04:19:15.000Z",
    slug: "how-do-you-create-a-before-and-after-slider-in-wix",
    sourceUrl: "https://zider.ink/question/how-do-you-create-a-before-and-after-slider-in-wix/",
    status: "published",
    tags: ["beforeafter slider x","before and after","wix"],
    title: "How Do You Create a Before and After Slider in Wix?",
    updatedAt: "2026-04-18T04:19:15.000Z",
  },
  {
    authorName: "yangxi",
    body: "<p>Yes, there are apps made for this purpose, and the right one depends on how simple you want the setup to be.</p>\n<p>For most Wix users, a good Before and After slider app should do three things well:</p>\n<p>it should be easy to install, easy to set up, and easy for visitors to use.</p>\n<p>A tool like <span><b>Before And After</b></span> is useful because it helps you create a clean image comparison section without needing custom code. This can be especially helpful for service businesses, agencies, designers, and anyone showing visual transformations.</p>\n<p><img src=\"https://static.wixstatic.com/media/46696d_0a04f05c8ef14a039321c1a1bd1ccfaf~mv2.png\" alt=\"\" />You can view the app here:</p>\n<p><a href=\"https://www.wix.com/app-market/before-and-after\">https://www.wix.com/app-market/before-and-after</a></p>",
    contentType: "forum",
    coverImageUrl: "https://static.wixstatic.com/media/46696d_0a04f05c8ef14a039321c1a1bd1ccfaf~mv2.png",
    createdAt: "2026-04-18T04:19:12.000Z",
    excerpt: "Yes, there are apps made for this purpose, and the right one depends on how simple you want the setup to be.For most Wix users, a good Before and After slider app should do three things well:it should be easy to install,",
    id: "community-question-is-there-a-good-before-and-after-slider-app-for-wix-websites",
    locale: "en",
    publishedAt: "2026-04-18T04:19:12.000Z",
    slug: "is-there-a-good-before-and-after-slider-app-for-wix-websites",
    sourceUrl: "https://zider.ink/question/is-there-a-good-before-and-after-slider-app-for-wix-websites/",
    status: "published",
    tags: ["beforeafter slider x","before and after","wix"],
    title: "Is There a Good Before and After Slider App for Wix Websites?",
    updatedAt: "2026-04-18T04:19:12.000Z",
  },
  {
    authorName: "yangxi",
    body: "<p>Wix does not always include a built-in Before and After slider as a default element in the editor, so many users look for an app instead.</p>\n<p>The easiest way is to search in the Wix App Market for a Before and After slider app. These apps are made specifically to help you add an image comparison section without building it from scratch.</p>\n<p>One option is <span><b>Before And After</b></span>, which is designed for Wix users who want to display two images with a draggable slider effect.</p>\n<p>App link:</p>\n<p><a href=\"https://www.wix.com/app-market/before-and-after\">https://www.wix.com/app-market/before-and-after</a></p>",
    contentType: "forum",
    coverImageUrl: null,
    createdAt: "2026-04-18T04:19:09.000Z",
    excerpt: "Wix does not always include a built-in Before and After slider as a default element in the editor, so many users look for an app instead.The easiest way is to search in the Wix App Market for a Before and After slider ap",
    id: "community-question-where-can-i-find-a-before-and-after-slider-on-wix-is-free",
    locale: "en",
    publishedAt: "2026-04-18T04:19:09.000Z",
    slug: "where-can-i-find-a-before-and-after-slider-on-wix-is-free",
    sourceUrl: "https://zider.ink/question/where-can-i-find-a-before-and-after-slider-on-wix-is-free/",
    status: "published",
    tags: ["beforeafter slider x","before and after","wix"],
    title: "Where Can I Find a Before and After Slider on Wix? is Free",
    updatedAt: "2026-04-18T04:19:09.000Z",
  },
  {
    authorName: "yangxi",
    body: "<img src=\"https://static.wixstatic.com/media/46696d_fe0eeee7d3564b35a167848a6e883f99~mv2.png\" alt=\"\" />\n<p> </p>\n<p>If you want to show visual differences clearly on a Wix website, a Before and After slider is one of the simplest options.</p>\n<p>It works well for website redesigns, renovation projects, beauty results, photo editing, cleaning services, and any other case where users need to compare two images side by side.</p>\n<p>A practical option is <span><b>Before And After</b></span> for Wix. It lets visitors drag a slider to compare two images in one interactive block, which makes the result easier to understand than showing two separate images.</p>\n<p>You can check it here:</p>\n<p><a href=\"https://www.wix.com/app-market/before-and-after\"><strong>https://www.wix.com/app-market/before-and-after</strong></a></p>",
    contentType: "forum",
    coverImageUrl: "https://static.wixstatic.com/media/46696d_fe0eeee7d3564b35a167848a6e883f99~mv2.png",
    createdAt: "2026-04-18T04:19:06.000Z",
    excerpt: "If you want to show visual differences clearly on a Wix website, a Before and After slider is one of the simplest options.It works well for website redesigns, renovation projects, beauty results, photo editing, cleaning",
    id: "community-question-what-is-the-best-wix-before-and-after-slider-for-showing-visual-comparisons",
    locale: "en",
    publishedAt: "2026-04-18T04:19:06.000Z",
    slug: "what-is-the-best-wix-before-and-after-slider-for-showing-visual-comparisons",
    sourceUrl: "https://zider.ink/question/what-is-the-best-wix-before-and-after-slider-for-showing-visual-comparisons/",
    status: "published",
    tags: ["beforeafter slider x","before and after","wix"],
    title: "What Is the Best Wix Before and After Slider for Showing Visual Comparisons?",
    updatedAt: "2026-04-18T04:19:06.000Z",
  },
  {
    authorName: "yangxi",
    body: "<p>I’m looking for a simple way to add a draggable Before &amp; After image slider to a Wix site.</p>\n<p>Main use cases would be things like website redesigns, renovations, photo edits, beauty results, or cleaning/repair work.</p>\n<p>I found this app, but I’m still checking if there are better options:</p>\n<p>https://www.wix.com/app-market/before-and-after?referral=zider.ink</p>\n<p>Has anyone used a Before &amp; After slider on Wix before? Any recommendations?</p>",
    contentType: "forum",
    coverImageUrl: null,
    createdAt: "2026-04-18T03:44:31.000Z",
    excerpt: "I’m looking for a simple way to add a draggable Before & After image slider to a Wix site.Main use cases would be things like website redesigns, renovations, photo edits, beauty results, or cleaning/repair work.I fou",
    id: "community-question-looking-for-a-simple-before-after-slider-app-for-wix",
    locale: "en",
    publishedAt: "2026-04-18T03:44:31.000Z",
    slug: "looking-for-a-simple-before-after-slider-app-for-wix",
    sourceUrl: "https://zider.ink/question/looking-for-a-simple-before-after-slider-app-for-wix/",
    status: "published",
    tags: ["beforeafter slider x","before and after","wix"],
    title: "Looking for a simple Before & After slider app for Wix",
    updatedAt: "2026-04-18T03:44:31.000Z",
  },
  {
    authorName: "yangxi",
    body: "<p>I’m looking for a simple way to show “before vs after” results on a Wix site.</p>\n<p>Main use cases would be things like renovation projects, website redesigns, photo edits, beauty results, or cleaning/repair work.</p>\n<p>I found this app, but I’m still checking if there are better options:</p>\n<p>https://www.wix.com/app-market/before-and-after?referral=zider.ink</p>\n<p>Has anyone used a Before &amp; After slider on Wix before? Any recommendations?</p>",
    contentType: "forum",
    coverImageUrl: null,
    createdAt: "2026-04-18T03:44:26.000Z",
    excerpt: "I’m looking for a simple way to show “before vs after” results on a Wix site.Main use cases would be things like renovation projects, website redesigns, photo edits, beauty results, or cleaning/repair work.I found this a",
    id: "community-question-how-do-you-show-renovation-or-redesign-results-on-a-wix-site",
    locale: "en",
    publishedAt: "2026-04-18T03:44:26.000Z",
    slug: "how-do-you-show-renovation-or-redesign-results-on-a-wix-site",
    sourceUrl: "https://zider.ink/question/how-do-you-show-renovation-or-redesign-results-on-a-wix-site/",
    status: "published",
    tags: ["beforeafter slider x","before and after","wix"],
    title: "How do you show renovation or redesign results on a Wix site?",
    updatedAt: "2026-04-18T03:44:26.000Z",
  },
  {
    authorName: "yangxi",
    body: "<p>Sync products, manage rich content, and edit with the built-in editor</p>\n<p>.<img src=\"https://assets.lopuo.com/app/zider/uploads/2026/03/Store-Content-Suite-app-3.png\" alt=\"\" /></p>\n<h3>Learn how to get started with Store Content Suite for Wix Stores.</h3>\n<p>In this tutorial, we’ll cover:</p>\n<ul>\n<li>How to install the Store Content Suite app</li>\n<li>How to sync Wix Store products</li>\n<li>How to edit and manage product content</li>\n</ul>\n<video src=\"https://video.wixstatic.com/video/46696d_26010525107e46b28049064fd16503f5/1080p/mp4/file.mp4?_=1\" controls></video>",
    contentType: "forum",
    coverImageUrl: "https://assets.lopuo.com/app/zider/uploads/2026/03/Store-Content-Suite-app-3.png",
    createdAt: "2026-03-29T06:55:21.000Z",
    excerpt: "Sync products, manage rich content, and edit with the built-in editor . Learn how to get started with Store Content Suite for Wix Stores. In this tutorial, we’ll cover: How to install the Store Content Suite app How to s",
    id: "widget-guide-store-content-suite",
    locale: "en",
    publishedAt: "2026-03-29T06:55:21.000Z",
    slug: "store-content-suite",
    sourceUrl: "https://zider.ink/wix-app-widgets/store-content-suite/",
    status: "published",
    tags: ["store content suite","product pages","wix"],
    title: "Store Content Suite",
    updatedAt: "2026-03-29T06:55:21.000Z",
  },
  {
    authorName: "yangxi",
    body: "<p>BeforeAfter Slider X is a powerful and easy-to-use widget for showcasing before-and-after images on your site. Perfect for portfolios, product demos, and visual comparisons, it features customizable divider styles, smooth label animations, and watermark control. Enhance your site’s interactivity and engage visitors with a professional, responsive slider. Premium users enjoy advanced customization and watermark-free display.<img src=\"https://assets.lopuo.com/app/zider/uploads/2026/03/image-b-a-3.jpg\" alt=\"\" /></p>\n<h3>Help&amp;How to work</h3>\n<video src=\"https://video.wixstatic.com/video/46696d_da4e72be512f4551b9148a508e37512d/1080p/mp4/file.mp4?_=1\" controls></video>",
    contentType: "forum",
    coverImageUrl: "https://assets.lopuo.com/app/zider/uploads/2026/03/image-b-a-3.jpg",
    createdAt: "2026-03-08T11:32:26.000Z",
    excerpt: "BeforeAfter Slider X is a powerful and easy-to-use widget for showcasing before-and-after images on your site. Perfect for portfolios, product demos, and visual comparisons, it features customizable divider styles, smoot",
    id: "widget-guide-beforeafter-slider-x",
    locale: "en",
    publishedAt: "2026-03-08T11:32:26.000Z",
    slug: "beforeafter-slider-x",
    sourceUrl: "https://zider.ink/wix-app-widgets/beforeafter-slider-x/",
    status: "published",
    tags: ["beforeafter slider x","before and after","wix"],
    title: "BeforeAfter Slider X",
    updatedAt: "2026-03-08T11:32:26.000Z",
  },
  {
    authorName: "yangxi",
    body: "<p><span><b>Zider Copy Button</b></span> helps you add a simple and customizable copy-to-clipboard button to your site. It is perfect for coupon codes, promo messages, links, email addresses, phone numbers, referral codes, product IDs, and other text your visitors may need to copy quickly.</p>\n<p>You can fully customize the button text, the value to copy, and the success message shown after clicking. The app also includes flexible design controls such as background color, success background color, text color, border radius, and font size, making it easy to match your site style.</p>\n<p>For layout and icon settings, you can choose the icon position (left, right, or top), adjust the gap between the icon and text, upload your own icon, preview it, or restore the default icon with one click.</p>\n<p>The app supports copy-to-clipboard functionality with a built-in compatibility fallback to improve reliability across different browser environments.</p>\n<hr />\n<p>1) Set Button Text and Value to Copy.</p>\n<p>2) Style colors and typography.</p>\n<p>3) Configure Layout + Icon Upload (Plus required).</p>\n<p>4) Click the button on site to copy the value.</p>\n<div style=\"width: 640px;\"><video src=\"https://video.wixstatic.com/video/46696d_5763450d2007484092ef11d986959753/1080p/mp4/file.mp4?_=1\" controls=\"controls\"></video></div>",
    contentType: "forum",
    coverImageUrl: null,
    createdAt: "2026-03-04T15:45:10.000Z",
    excerpt: "Zider Copy Button helps you add a simple and customizable copy-to-clipboard button to your site. It is perfect for coupon codes, promo messages, links, email addresses, phone numbers, referral codes, product IDs, and oth",
    id: "community-question-zider-copy-button",
    locale: "en",
    publishedAt: "2026-03-04T15:45:10.000Z",
    slug: "zider-copy-button",
    sourceUrl: "https://zider.ink/question/zider-copy-button/",
    status: "published",
    tags: ["copy button","clipboard","wix"],
    title: "Zider Copy Button",
    updatedAt: "2026-03-04T15:45:10.000Z",
  },
  {
    authorName: "yangxi",
    body: "<img src=\"https://static.wixstatic.com/media/46696d_9cecca0af5f04439be6fe93bc307cae9~mv2.png/v1/fill/w_1143,h_257,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/before-and-after_App-001.png\" alt=\"\" />\n<p><span>New Here，Hope it can help u ～</span></p>\n<div id=\"viewer-hpinz4520\" dir=\"auto\">Demo：</div>\n<div dir=\"auto\"></div>\n<blockquote>\n<div dir=\"auto\"><a href=\"https://hellozider.wixstudio.com/zider/before-and-after\">https://hellozider.wixstudio.com/zider/before-and-after</a></div>\n</blockquote>\n<div dir=\"auto\"></div>\n<div dir=\"auto\"></div>\n<h2 dir=\"auto\"><span><strong>Best Practice</strong></span></h2>\n<div id=\"viewer-7sqjm2229\" dir=\"auto\"></div>\n<div id=\"viewer-jh4t22230\" dir=\"ltr\">\n<blockquote>\n<div id=\"viewer-8d4ko2231\" dir=\"auto\"><span><strong>Keep all images consistent.</strong>For product shots or interior design photos, use the same dimensions and camera angles so your site maintains a clean, professional look.</span></div>\n</blockquote>\n</div>\n<div dir=\"auto\">\n<h2 id=\"viewer-w207b2998\" dir=\"auto\"><span><strong>📹 Video Tutorial</strong></span></h2>\n<p><span>For the step-by-step written guide, please continue reading below.</span></p>\n<div id=\"viewer-94ydy3376\" dir=\"auto\"><video controls=\"controls\"><span data-mce-type=\"bookmark\" style=\"display: inline-block; width: 0px; overflow: hidden; line-height: 0;\">﻿</span><source src=\"https://video.wixstatic.com/video/46696d_878c4c63a0784c15a06d50772f24b5fb/1080p/mp4/file.mp4\" type=\"video/mp4\" /></video></div>\n</div>\n<p>&nbsp;</p>\n<h2 id=\"viewer-jrlhk3196\" dir=\"auto\">View the illustrated tutorial</h2>\n<div id=\"viewer-h3mvc2337\" dir=\"auto\"><span> </span></div>\n<p id=\"viewer-wi2hi139\" dir=\"auto\"><span><strong>1、Add App Elements</strong></span></p>\n<p><span> In the Wix Editor, click the “+ Add Elements” icon on the left.</span></p>\n<div id=\"viewer-g7t6c143\" dir=\"auto\"><span> </span></div>\n<div id=\"viewer-j596y2199\">\n<div>\n<figure data-hook=\"figure-IMAGE\">\n<div data-hook=\"image-viewer\">\n<div id=\"j596y2199\" data-hook=\"image-viewer-j596y2199\"><img src=\"https://static.wixstatic.com/media/46696d_a33589e000144d37b22958971ce9dace~mv2.png/v1/fill/w_1143,h_590,al_c,q_90,usm_0.66_1.00_0.01,enc_auto/46696d_a33589e000144d37b22958971ce9dace~mv2.png\" alt=\"ree\" /></div>\n</div>\n</figure>\n</div>\n</div>\n<div id=\"viewer-ulkce244\" dir=\"auto\"><span> </span></div>\n<p id=\"viewer-rawfo245\" dir=\"auto\"><span><strong>2、Open the Media Manager</strong></span></p>\n<div id=\"viewer-kcuwk274\">\n<div>\n<figure data-hook=\"figure-IMAGE\">\n<div data-hook=\"image-viewer\">\n<div id=\"kcuwk274\" data-hook=\"image-viewer-kcuwk274\"><img src=\"https://static.wixstatic.com/media/46696d_03cbc6d1eed34c9fa4eea13198684bbe~mv2.png/v1/fill/w_1143,h_590,al_c,q_90,usm_0.66_1.00_0.01,enc_auto/46696d_03cbc6d1eed34c9fa4eea13198684bbe~mv2.png\" alt=\"ree\" /></div>\n</div>\n</figure>\n</div>\n</div>\n<div id=\"viewer-tw-target-rmn\" dir=\"auto\"><span> </span></div>\n<p id=\"viewer-s6gdu637\" dir=\"auto\"><span><strong>3、Locate Your File</strong></span></p>\n<div id=\"viewer-nzvig1057\" dir=\"auto\"><span> </span></div>\n<p><span>If there is no picture, please upload it first</span></p>\n<div id=\"viewer-3d6t41058\" dir=\"auto\"><span> </span></div>\n<ul>\n<li dir=\"auto\" aria-level=\"1\"><span>In the Media Manager sidebar, go to Manage → Site Files.</span></li>\n<li dir=\"auto\" aria-level=\"1\"><span>Hover over the file whose URL you need and click the ••• menu that appears.</span></li>\n</ul>\n<div id=\"viewer-srpve1985\" dir=\"auto\"><span> </span></div>\n<div id=\"viewer-4nppv2001\" dir=\"auto\"><span> </span></div>\n<div id=\"viewer-89glr2021\">\n<div>\n<figure data-hook=\"figure-IMAGE\">\n<div data-hook=\"image-viewer\">\n<div id=\"89glr2021\" data-hook=\"image-viewer-89glr2021\"><img src=\"https://static.wixstatic.com/media/46696d_3fd707b00cf74b4397c1916369c98a66~mv2.png/v1/fill/w_1143,h_590,al_c,q_90,usm_0.66_1.00_0.01,enc_auto/46696d_3fd707b00cf74b4397c1916369c98a66~mv2.png\" alt=\"ree\" /></div>\n</div>\n</figure>\n</div>\n</div>\n<p id=\"viewer-8yh6k2032\" dir=\"auto\"><span><strong>4. Copy the URL</strong></span></p>\n<ul>\n<li dir=\"auto\" aria-level=\"1\"><span>From the dropdown, select <strong>“Copy URL”</strong>.</span></li>\n<li dir=\"auto\" aria-level=\"1\"><span>The file’s direct link is now on your clipboard—ready to paste .</span></li>\n</ul>\n<div id=\"viewer-gk8uj1355\" dir=\"auto\"><span> </span></div>\n<p id=\"viewer-rhaib1375\" dir=\"auto\"><span><strong>5. </strong><strong>Paste the Url</strong></span></p>\n<div id=\"viewer-z6pz11391\" dir=\"auto\"><span> </span></div>\n<div id=\"viewer-9qqz52161\">\n<div>\n<figure data-hook=\"figure-IMAGE\">\n<div data-hook=\"image-viewer\">\n<div id=\"9qqz52161\" data-hook=\"image-viewer-9qqz52161\"><img src=\"https://static.wixstatic.com/media/46696d_c8398ce7e8c14c6b8e5008e2a4a61d34~mv2.png/v1/fill/w_1143,h_590,al_c,q_90,usm_0.66_1.00_0.01,enc_auto/46696d_c8398ce7e8c14c6b8e5008e2a4a61d34~mv2.png\" alt=\"ree\" /></div>\n</div>\n</figure>\n</div>\n</div>\n<div id=\"viewer-bfnuw281\" dir=\"auto\"></div>\n<div dir=\"auto\"></div>",
    contentType: "forum",
    coverImageUrl: "https://static.wixstatic.com/media/46696d_9cecca0af5f04439be6fe93bc307cae9~mv2.png/v1/fill/w_1143,h_257,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/before-and-after_App-001.png",
    createdAt: "2025-12-10T05:33:23.000Z",
    excerpt: "New Here，Hope it can help u ～ Demo： https://hellozider.wixstudio.com/zider/before-and-after Best Practice Keep all images consistent.For product shots or interior design photos, use the same dimensions and camera angles",
    id: "community-question-how-to-set-before-and-after",
    locale: "en",
    publishedAt: "2025-12-10T05:33:23.000Z",
    slug: "how-to-set-before-and-after",
    sourceUrl: "https://zider.ink/question/how-to-set-before-and-after%ef%bc%9f/",
    status: "published",
    tags: ["beforeafter slider x","before and after","wix"],
    title: "How to Set Before and After？",
    updatedAt: "2025-12-10T05:33:23.000Z",
  },
  {
    authorName: "yangxi",
    body: "<p><iframe src=\"https://www.youtube.com/embed/GdubbsSq_yA?si=LszntSRoJMJ0aKWM\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe></p>",
    contentType: "forum",
    coverImageUrl: null,
    createdAt: "2025-12-01T08:33:29.000Z",
    excerpt: "How to used Zider Logo Loop",
    id: "community-question-how-to-used-zider-logo-loop",
    locale: "en",
    publishedAt: "2025-12-01T08:33:29.000Z",
    slug: "how-to-used-zider-logo-loop",
    sourceUrl: "https://zider.ink/question/how-to-used-zider-logo-loop/",
    status: "published",
    tags: ["loop logo","carousel","wix"],
    title: "How to used Zider Logo Loop",
    updatedAt: "2025-12-01T08:33:29.000Z",
  },
  {
    authorName: "yangxi",
    body: "<div>\n<div>\n<div>\n<div>\n<div></div>\n</div>\n</div>\n</div>\n</div>\n<div>\n<div>\n<div>\n<div dir=\"auto\" data-message-author-role=\"assistant\" data-message-id=\"e808e19f-0220-4af6-b553-f448dafa0e8b\" data-message-model-slug=\"gpt-4o\">\n<div>\n<div>\n<p>&nbsp;</p>\n<p>Welcome to our community forum! To ensure a positive and productive environment, please adhere to the following guidelines when participating:</p>\n<ol>\n<li><strong>Clearly State Your Questions</strong>\n<ul>\n<li>Provide detailed information about your issue or question.</li>\n<li>Include any relevant examples, screenshots, or error messages to help others understand and assist you effectively.</li>\n</ul>\n</li>\n<li><strong>Be Respectful and Courteous</strong>\n<ul>\n<li>Treat</li>\n<li>Avoid offensive language, personal attacks, or di</li>\n</ul>\n</li>\n<li><strong>Stay on Topic</strong>\n<ul>\n<li>Post your questions or comments in the appro</li>\n<li>Keep discussions relevant to the topic a</li>\n</ul>\n</li>\n<li><strong>No Spam or Self-Promotion</strong>\n<ul>\n<li>Refrain from posting advertisements, affiliate links, or excessive promotions.</li>\n<li>Share knowledge and contribute meaningfully to discussions.</li>\n</ul>\n</li>\n<li><strong>Follow Forum-Specific Rules</strong>\n<ul>\n<li>Check for any additional rules or pinned posts in sp</li>\n<li>Adhere to the guidelines set by moderators fo</li>\n</ul>\n</li>\n</ol>\n<p>Failure to comply with these rules may result in warnings, post removal, or account suspension. Let’s work together to make this forum a helpful and engaging place for everyone</p>\n<p>Thank you for your cooperation!<br />\n<strong>Zider Team</strong></p>\n</div>\n</div>\n</div>\n</div>\n</div>\n</div>",
    contentType: "forum",
    coverImageUrl: null,
    createdAt: "2024-12-13T14:01:38.000Z",
    excerpt: "Welcome to our community forum! To ensure a positive and productive environment, please adhere to the following guidelines when participating: Clearly State Your Questions Provide detailed information about your i",
    id: "community-question-forum-announcement",
    locale: "en",
    publishedAt: "2024-12-13T14:01:38.000Z",
    slug: "forum-announcement",
    sourceUrl: "https://zider.ink/question/forum-announcement/",
    status: "published",
    tags: ["community"],
    title: "Forum Announcement",
    updatedAt: "2024-12-13T14:01:38.000Z",
  },
  {
    authorName: "yangxi",
    body: "<pre id=\"tw-target-text\" dir=\"ltr\" data-placeholder=\"翻译\" data-ved=\"2ahUKEwjckJ3dsoaKAxUyslYBHUWAKxYQ3ewLegQIDBAU\" aria-label=\"译文：If you have any questions, you can leave a message\"><span lang=\"en\">If you have any questions, you can leave a message</span></pre>",
    contentType: "forum",
    coverImageUrl: null,
    createdAt: "2024-12-01T10:49:46.000Z",
    excerpt: "If you have any questions, you can leave a message",
    id: "community-question-wix-support",
    locale: "en",
    publishedAt: "2024-12-01T10:49:46.000Z",
    slug: "wix-support",
    sourceUrl: "https://zider.ink/question/wix-support/",
    status: "published",
    tags: ["community"],
    title: "Wix Support",
    updatedAt: "2024-12-01T10:49:46.000Z",
  }
];

export const sampleForumEntries = sampleForumEntryItems.map(normalizeCmsEntryAssetUrls).sort(
  (firstEntry, secondEntry) =>
    Date.parse(secondEntry.publishedAt || secondEntry.updatedAt) - Date.parse(firstEntry.publishedAt || firstEntry.updatedAt),
);

export function getSampleForumEntry(slug: string) {
  return sampleForumEntries.find((entry) => entry.slug === slug) ?? null;
}
